### ISSUE TITLE
Help area extension

### ISSUE THREAD

**Issue by vins31** [twitwi/deck.js#26]
At the moment the Help Area extension only displays this when the key "h" is pressed.

```Help, Tools and Configuration
Keys
H
Toggle this help area
Session Variables
```

Is it normal or a bug?

**Comment by twitwi** [comment]
It's normal.
The extension is very new and design as a container for other extensions to contribute to.
To have more matter in this help area, the other extensions need to be updated.

I'm keeping this issue open as a reminder to update other extensions, following the model of https://github.com/twitwi/deck.js/commit/60e02d0d980c7a5049190b100748b04d1ab44d55#diff-cd60c3651b53946b536b6216ad33831eR23

**Comment by twitwi** [comment]
Some of the extensions are now registering their keys to the help area (this is now also included in the https://github.com/twitwi/deck.js-starterkit/ and the https://github.com/twitwi/deck.js-packed version).

Example of how to add the registration in a backward compatible manner:
https://github.com/twitwi/deck.js/commit/3b073d99eee654c532966275004ef5deae31e388

There are probably extensions that still need to register their keys but I'm closing this for now (it is now better to have extension-specific issues).
